openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
    /customers:
      get:
        description: ""
        responses:
          "200":
            description: "OK"
            content:
              text/plain:
                schema:
                  type: "string"
                examples:
                  Example#1:
                    value: "Loading Customers....."
      post:
        description: ""
        requestBody:
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Indiviual"
          required: true
        responses:
          "200":
            description: "OK"
            content:
              '*/*':
                schema: { }
  components:
    schemas:
      Address:
        type: "object"
        properties:
          doorNo:
            type: "string"
          streetName:
            type: "string"
      Indiviual:
        type: "object"
        properties:
          surName:
            type: "string"
          gender:
            type: "string"
            enum:
              - "MALE"
              - "FEMALE"
              - "TRANS"
          dob:
            type: "string"
            format: "date"
          name:
            type: "string"
          accNo:
            type: "integer"
            format: "int64"
          email:
            type: "string"
          pass:
            type: "string"
          contactNo:
            type: "integer"
            format: "int64"
          address:
            $ref: "#/components/schemas/Address"
      ResponseWrapper:
        type: "object"
        properties:
          message:
            type: "string"
      ResponseWrapper_Indiviual:
        type: "object"
        properties:
          message:
            type: "string"
          payload:
            $ref: "#/components/schemas/Indiviual"
      ResponseWrapper_String:
        type: "object"
        properties:
          message:
            type: "string"
          payload:
            type: "string"
components:
  schemas:
